algoritmo "Soma de números"
// Função : Solicita dois números para o usuário e mostra soma deles
// Autor :Gustavo Guanabara
// Data : 28/02/2022
var
   numero1, numero2, soma: inteiro
inicio
      Escreva("Digite um número: ")
      Leia(numero1)
      Escreva("Digite outro número: ")
      Leia(numero2)
      soma <- numero1 + numero2
      Escreva("A soma entre o ", numero1, " e o ", numero2, " é ", soma)
fimalgoritmo
