algoritmo "Função Somar dois valores"
// Função : Uma função que soma dois números
// Autor :
// Data : 21/04/2022
var
Plus, numero1, numero2: inteiro
   Funcao Soma(number1, number2: inteiro): inteiro
   Inicio
         Plus <- number1 + number2
         retorne Plus
   FimFuncao
inicio
      numero1 <- 5
      numero2 <- 4
      Plus <- Soma(numero1, numero2)
      Escreval("A soma dos números ", numero1, " +", numero2, " é ", Plus)
fimalgoritmo
