algoritmo "Creuza vai fazer aniversário (creuza01)"
// Função : informa quantas velas será colocado no bolo da creuza.
// Autor : Gustavo Guanabara
// Data : 10/03/2022
var
   ano_atual, ano_nascimento, idade: inteiro
inicio
      Escreval("Em que ano nós estamos? ")
      Leia(ano_atual)
      Escreval("Em que ano a Creuza nasceu")
      Leia(ano_nascimento)
      idade <- ano_atual - ano_nascimento)
      Escreval("Minha idade será ", idade, " anos.")
fimalgoritmo
